### ISSUE TITLE
request for adding port abilty

### ISSUE THREAD

**Issue by itaiber2000** [sestus/godyndns#1]
hi,
will it be possible to update the subdomain with a specific port?
example, i have two subdomains that i want to re direct to the same dynamic ip  but for different
instanes services on my server?
like: a.mydomain.com -> 10.10.10.11:8096
and  b.mydomain.com -> 10.10.10.11:445

thanks in advance,
itai.

**Comment by sestus** [comment]
Hey @itaiber2000. Thanks for reaching out!

I don't think that what you're describing can be done via DNS. A DNS record maps a name to an IP address - you can't have a port in there.
