### ISSUE TITLE
Remove Hardcoded domain name

### ISSUE THREAD

**Issue by jcekstrom** [sestus/godyndns#2]
https://github.com/sestus/godyndns/blob/2afd8da227c05fa4b5e1ed5f9ee8cf2313ac57f6/godyndns.go#L59

Cool project.  I would suggest removing the hard coded domain name, and instead pulling it off of the hostname.

**Comment by sestus** [comment]
Hey, thanks for raising this!

Indeed, I intented to remove my own domain from the code but it turns out I never did it. Will remove that and release a new version.

**Comment by sestus** [comment]
Hey @jcekstrom , I have now removed the hardcoded url as discussed. Also added some extra checks on the subdomain given by the user. Feel free to have a look at the linked PR should you wish to do so.

**Comment by jcekstrom** [comment]
Looks good.
