### ISSUE TITLE
Dynamic Bare Domain

### ISSUE THREAD

**Issue by riley-hayes** [sestus/godyndns#4]
Is it possible to have @ as a subdomain? I have tried but it errors out every time building it
From --subdomain=@.example.org
2021/02/07 15:13:45 Couldn't construct domain from @.example.org : publicsuffix: empty label in domain ".example.org"
2021/02/07 15:13:45 Failed to get A record as I couldn't extract the domain from @.example.org
2021/02/07 15:13:45 Failed to get the GoDaddy A Record : publicsuffix: empty label in domain ".example.org".

Side note: Domain is redacted for privacy

**Comment by sestus** [comment]
Hey @riley-hayes , thanks for raising this. To be honnest, I haven't thought about that, but I guess your use case is valid - we may as well update the bare domain, and not some sub-domain of it.

Let me work on this and when it's ready I am going to release a new version.

**Comment by riley-hayes** [comment]
Hi @sestus, sorry for the delay (I didn't realise you edited your post :P)

I would imagine it would either be like `--subdomain=@.example.org` or `--domain=example.org`.
The reason I mention @ is because that is how you declare it in the DNS config page, but you could have it read both (long-winded way could be `--domain=example.org --subdomain=mail`, or just if there's no preceding subdomain, or the subdomain is `@.` then just update the bare domain)

If I get a chance I might make a pull request, I'm not too familiar with coding myself but there's always a chance to learn :)

**Comment by sestus** [comment]
hey @riley-hayes, this is now implemented. As discussed, updated the --subdomain to --domain (Update the instructions accordingly), so you can now update your root domain by doing `--domain=example.org` or `--domain=@.example.org`. 

Feel free to give it a try, and please let me know if it doesn't work as expected
